 CREATE TABLE CUST (CUSTOMER_ID int, CUSTOMER_NAME VARCHAR2(50),CUSTOMER_ADDR  VARCHAR2(250));
 CREATE TABLE CUST_TRANS (TRANSACTION_ID int,CUSTOMER_ID int ,SPENT_DETAILS VARCHAR(250),TRANSACTION_DATE DATE,AMOUNT int);
 INSERT INTO CUST(CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDR) values (1,'cust1','xxx');
 INSERT INTO CUST(CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDR) values (2,'cust2','yyy');
 INSERT INTO CUST(CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_ADDR) values (3,'cust2','zzz');
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (1,1,'grocery','2024-08-12',120);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (2,1,'fruits','2024-07-07',85);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (3,1,'vegetables','2024-06-06',160);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (4,1,'vegetables','2024-09-01',160);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (5,2,'grocery','2024-08-12',50);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (6,2,'fruits','2024-07-07',10);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (7,2,'vegetables','2024-06-06',60);
 INSERT INTO CUST_TRANS(TRANSACTION_ID,CUSTOMER_ID,SPENT_DETAILS,TRANSACTION_DATE,AMOUNT) VALUES (8,2,'vegetables','2024-09-01',60);

 COMMIT;